apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
spec:
  selector:
    io.kompose.service: octopus-server
  ports:
    - port: 8080
      targetPort: 8080
      name: http-port
    - port: 10943
      name: octo-port
  type: LoadBalancer